### ISSUE TITLE
Make failing to to compile due to missing -lgnublin

### ISSUE THREAD

**Issue by SgtBurned** [cburki/gnublin-modules#2]
Compiling in gnublin-modules I receive an error which states;

/usr/bin/ld: cannot find -lgnublin

whilst compiling the module_sc16is750_uart.o
I have install gnublin-api, gnublin-make, and gnublin-modules all with correct Config files and it passes all files in the SC16IS7xx Folder except the UART one.

**Comment by cburki** [comment]
Hi,

Did you have the gnublin.so.1.0.1 file in the gnublin-api folder ? If not, you first need to build the "gnublin-api". If yes, this mean that the GNUBLINAPIDIR path is not set correctly. Does the GNUBLINAPIDIR point to the gnublin-api folder ?

Best regards,
Christophe

**Comment by SgtBurned** [comment]
I have a libgnublin.s0.1.0.1 ( No gnublin.so.1.0.1 ) and the GNUBLINAPIDIR path is set right and points to the API folder.

**Comment by cburki** [comment]
The file is not named correctly. I do not know why, this file is created during the build of "gnublin-api". Try to rename it from libgnublin.s0.1.0.1 to gnublin.so.1.0.1.

**Comment by SgtBurned** [comment]
Still fails to find -lgnublin after renaming. The libgnublin.so.1.0.1 was made during the make in the gnublin-api folder.

**Comment by cburki** [comment]
Could you please send me a trace of the compilation ? Go into the module_sc16is7x0 folder and execute make.

**Comment by cburki** [comment]
Did you have the libgnublin.a file or only the gnublin.a inside the gnublin-api folder ? If you only have the gnublin.a, try to copy it to libgnublin.a.

**Comment by SgtBurned** [comment]
it passes if I copy the gnublin.a to libgnublin.a I think that was the problem.

**Comment by cburki** [comment]
Good news, yes it was the problem. I just remembered that I have modified the gnublin-api Makefile to automatically copy it. I think this is an error from the gnublin-api distribution.

Best regards,
Christophe
